<?php

namespace EpopeeBundle\Repository;

/**
 * Reflection2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Reflection2Repository extends \Doctrine\ORM\EntityRepository
{
}
